### ISSUE TITLE
ranks info

### ISSUE THREAD

**Issue by Kadamitas** [FTBTeam/FTB-Utilities#1043]
I was redirected here for ranks info, I click on wiki, it doesn't exist, I click on the link to /pages/ranks, it doesn't exist. Where can I read documentation. I just wanna make it so everyone has 5 homes, no cooldown on any commands, and 1000 chunks to claim. 

Every guide says to change ranks.json and do curly brace edits, this file doesn't exist, theres a ranks.text which redirects to nowhere, a player_ranks.text, and all permissions.

**Comment by jelaw21** [comment]
https://github.com/FTBTeam/FTB-Ranks/wiki

**Comment by Charmanth** [comment]
Also the ranks.json was changed to a txt file.  I was confused when I updated FTBUtilities from a version that used the json to a version that uses the txt.

It would be helpful if getting to documentation on everything was easier, because googling it is confusing, and not all the links in the more obvious places are updated.  :c
