### ISSUE TITLE
Reimplement chunkloading expiration timer

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Utilities#585]

**Comment by MindThoth** [comment]
Wait so don't have the chunk loading expiration? So like right now it's either you have offline chunk loading or not? The option to have your chunk loaded for a few hours after you logged off isn't working?

**Comment by LatvianModder** [comment]
Yeah, I disabled it around 1.10, it caused more problems than solved back then. Now it's different, the mod is a lot better (even though still broken in some places), so this feature might come back

**Comment by Tander** [comment]
Want this feature. Even two:
1. Unload chunks after some hours player offline.
2. Uncheck chunkloading flag if player wasn't online for some days (especially if this will be easier to implement).

And thanks for the ~~fish~~ mod! It's awesome and musthave in my packs =)

**Comment by LatvianModder** [comment]
I dont think `Uncheck chunkloading flag` is a good idea, that would cause confusion and people would think its a bug that their chunks are reset (it was an actual bug not too long ago)

**Comment by Mochnant** [comment]
I think it would be a better idea to just suppress the loading on a player's chunks, rather than resetting their actual flag, which would be confusing.  The idea and overall goal being you could say "suppress loaded chunks after 2 days" and "expire chunk claim after 30 days".  This way, a player who logged in every other day could keep their chunks loaded infinitely, but if they were gone for a week, when they logged back in, their chunks would reload and they could pick right back up with no changes to make.

**Comment by PhanaticD** [comment]
is there a manual way to do this since this isnt added yet

**Comment by LatvianModder** [comment]
It shouldnt be too hard to reimplement now that I have a new ranks system. Previously it was too broken, I just forgot about this issue :P

**Comment by PhanaticD** [comment]
okay great could really use this to help with my server as its just been more and more people over time

**Comment by instinxx** [comment]
Would like to have this reimplemented still.

**Comment by KindarConrath** [comment]
Came by just to make this issue, turns out it's already here, so I'll add my voice to those of people who want it.

I also think it could be good to have 2 tiers of chunk loading, an always loaded and an online/expiring load, each with their own limits. That way I could have 5 chunks that don't unload and a bunch of others that only stay loaded if I'm online, or within a few hours of me being online.

**Comment by PhanaticD** [comment]
1 year later

**Comment by LatvianModder** [comment]
Nothing compared to this https://github.com/LatvianModder/FTBUtilities/issues/88
