### ISSUE TITLE
Server owned chunks

### ISSUE THREAD

**Issue by TehStoneMan** [FTBTeam/FTB-Utilities#88]
I would like to make a suggestion for server owned chunks. The idea is that these chunks would be claimed by the sever, and can be grouped under different labels.
This would allow server admins to define community areas that can't be claimed by individual players, and by being assigned to a group, each group can have a different name and set of permissions.
For example, setting a "Spawn Town" where only the server ops can build.

**Comment by Dijkstra1** [comment]
I have had the same idea, admin would be able claim chunks as the server, individual to there own, as TehStoneMan only admin should be able build unless configured otherwise, but chest should/inventories should be accessible to all.

**Comment by Fearzu** [comment]
I second this.

**Comment by Speedy321** [comment]
I was thinking of logging in under a fake player name to do what effectively would be that.Or changing stuff in the files to fake a player claim, but it's bad and doesn't quite work, so if this gets implemented, i'll be really happy ;) 
TL:DR +1

**Comment by LatvianModder** [comment]
I've had this feature in To-Do list for the longest time, but this will only go in 1.9+ versions, since 1.7.10 is feature-locked. And it would probably break surprisingly well working current version

**Comment by IdrisDose** [comment]
Sorry for Necro, does this feature work.

**Comment by LatvianModder** [comment]
Server owned chunks / towns are coming soon, I already have some things in to that in future

**Comment by TomberWolf** [comment]
Is this implemented for 1.10.2?
We need to protect the spawn area with some custom flags.

**Comment by LatvianModder** [comment]
This is on my local ToDo list so there's a good chance it will get implemented in next 10 years
![Image](http://ss.latmod.com/pc/2017-04-14_20.08.03.png)

**Comment by gdude2002** [comment]
Any movement on this, friendo?

**Comment by GazbonicAcid** [comment]
welp, seems @LatvianModder has abandoned adding this feature

**Comment by GazbonicAcid** [comment]
@LatvianModder a server/op/admin claim fully separate from normal player claiming needs to be a top priority.
This is far more important then an in-game editor.

**Comment by ktole1999** [comment]
in your opinion this may be a top priority. not all feel that way. rather than dictate to a dev what his priorities should be maybe you could show more respect. just my 2 cents.

**Comment by LatvianModder** [comment]
I have already marked this as Important, so that means soon™ but there are more important-er things I need to make before this can happen. The *idea* sounds simple, but before this I have to make Admin Panel (done), conditional ranks, small claims gui redesign, server owned fake teams (because chunks need an owner), etc. So its not a one step thing, ya know

**Comment by EnderGamingFilms** [comment]
Some of us kinda get that, but the mod you have made is awesome and is helping me a lot with my server by replacing some plugins. So thanks for your hard work 👍

**Comment by kreezxil** [comment]
Can we move this to HIGH PRIORITY?

**Comment by LatvianModder** [comment]
It already is Important

**Comment by system-operator** [comment]
+1

**Comment by thetakodev** [comment]
This is a must-have feature! I would like to make a separate team for some claims, for sake of RP, and not sharing it with my team in my survival.

**Comment by P3rf3ctXZer0** [comment]
Any update on this? Admin claims prevent spawn griefing while allowing players to play uninterrupted. This also allows for safe server spawns. (This is not an attempt to push devs - its just this feature is the only one I care about because it is the only one I cannot find as polished anywhere else. Forge is just more stable overall.)

**Comment by Heyo13579** [comment]
bump

**Comment by LatvianModder** [comment]
Nope, still Latvian lol. I will maybe split it in feb, when I have more free time because FTB Quests basically takes 100% of my workdays

**Comment by P3rf3ctXZer0** [comment]
I have not toyed with FTB quests what makes it better than BetterQuesting?

**Comment by kreezxil** [comment]
Ease of quest creation.

like better questing as OP you enter editing mode with a command and then
that's where the similarities end.

1. open the quest panel
1. click on the green plus sign on the top to start a new quest line (page)
1. right click the new tab and choose properties from the context menu
1. change the icon to something representative of the quest line
1. click description and describe the quest line
1. hit ESC to back out of screen, green check to save changes, red x is the
same as ESC
1. now right click in the blank panel body and choose the quest action type
(item, xp, kill, etc)
1. as you did with the tab, right click the element that appeared and
choose a thing, like you can rename it, change the icon, describe it etc,
even move it.

FTB Quests reuses it's own mechanics for all of it's sub-functions, that
makes it very attractive to me and it means I don't have to learn something
new. So once you learn how to manipulate a tab icon and description your
50% skilled for the rest of the development.

There's apparently a lot of people hours invested in making it intuitive.

And it makes linking the elements easy as pie too. You got two elements on
the panel. Assume the first one is wood log and the second one is wood
sword. If  you want to require that wood log be done before the sword, the
first you click on the wood log so that it is hilited then you right click
on the sword and choose "set selected as dependency" and instantly a line
appears with direction indicator pointing at the sword.

If you move the the elements around the lines readjust.

another way to think about it, it's so easy to use that someone can reply
to you in text and explain it without using a video.

**Comment by P3rf3ctXZer0** [comment]
@LatvianModder thanks for the information

**Comment by LatvianModder** [comment]
Moved to new repo
